module.exports = [
    {
      id: 1,
      name: "Juan Uribe",
      country: "Colombia",
      startDate: "2021-02-02",
      endDate: null,
      terminationPeriod: 30,
      role: "Full Stack Developer",
      milestone: "Take MVP to a fully functional Beta",
      milestoneDescription: "We now understand that we have product market fit and would like to take our product to the next level by building out a fully functional beta that can support 10,000 users / day",
      prefCurrency: "COP",
      paymentAmount: 250000,
    },
    {
      id: 2,
      name: "Frans Micha",
      country: "Netherlands",
      startDate: "2021-08-05",
      endDate: null,
      terminationPeriod: 25,
      role: "Data Scientist",
      milestone: "Create road map to monetize data",
      milestoneDescription: "We have an incredible amount of data, and require the implementation of a road map to leverage this data for monetary gains",
      prefCurrency: "EUR",
      paymentAmount: 30000,
    },
]