module.exports = [
    {
      id: 1,
      name: "Juan Uribe",
      country: "Colombia",
      startDate: "2021-02-02",
      endDate: null,
      terminationPeriod: 30,
      jobTitle: "Full Stack Developer",
      milestone: "Take MVP to a fully functional Beta",
      milestoneDescription: "We now understand that we have product market fit and would like to take our product to the next level by building out a fully functional beta that can support 10,000 users / day",
      prefCurrency: "COP",
      paymentAmount: 10000,
      users_id: 1,
    },
    {
      id: 2,
      name: "Frans Micha",
      country: "Netherlands",
      startDate: "2021-08-05",
      endDate: "2022-04-05",
      terminationPeriod: 25,
      jobTitle: "Data Scientist",
      milestone: "Create road map to monetize data",
      milestoneDescription: "We have an incredible amount of data, and require the implementation of a road map to leverage this data for monetary gains",
      prefCurrency: "EUR",
      paymentAmount: 30000,
      users_id: 1,
    },
    {
      id: 3,
      name: "James Lorenzi",
      country: "Albania",
      startDate: "2021-09-15",
      endDate: "2022-08-05",
      terminationPeriod: 25,
      jobTitle: "Head of Marketing",
      milestone: "Launch Google Ads Campaign",
      milestoneDescription: "Create an iterative google ads strategy to increase business reach",
      prefCurrency: "ALL",
      paymentAmount: 2000,
      users_id: 1,
    }
]